<?php

namespace Modules\Auth;

use Illuminate\Foundation\Support\Providers\RouteServiceProvider as ServiceProvider;
use Illuminate\Support\Facades\Route;

class RouteServiceProvider extends ServiceProvider
{

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function map()
    {
        $this->mapWebRoutes();
        $this->mapAdminRoutes();
        $this->mapApiRoutes();
        $this->mapAuthRoutes();
    }

    protected function mapWebRoutes()
    {
        Route::middleware('web')
            ->group(__DIR__ . '/Routes/web.php');
    }

    protected function mapAdminRoutes()
    {
        Route::middleware('web')
            ->group(__DIR__ . '/Routes/admin.php');
    }

    protected function mapApiRoutes()
    {
        Route::prefix('api')
            ->group(__DIR__ . '/Routes/api.php');
    }

    protected function mapAuthRoutes()
    {
        Route::middleware('web')
            ->group(__DIR__ . '/Routes/auth.php');
    }

}
